"""
Batch script template generator for SSHWrite.

Generates hardened shell scripts for multi-file write operations.
The agent provides ONLY data (paths + content); the script structure,
error handling, backup logic, and rollback are hardcoded here.

Security invariants:
- Script template is Python code, never LLM-generated
- Content is injected as heredocs with unique delimiters
- Script self-deletes after execution
- Snapshot-first: ALL originals backed up BEFORE any modification
- Trap-based rollback on ANY failure
"""
from __future__ import annotations

import hashlib
import json
from datetime import datetime, timezone
from pathlib import PurePosixPath
from typing import Any


def _posix_basename(path: str) -> str:
    """Extract filename from an absolute POSIX path."""
    return PurePosixPath(path).name


def _posix_parent(path: str) -> str:
    """Extract parent directory from an absolute POSIX path.

    Returns '/' for top-level files like '/foo'.
    """
    return str(PurePosixPath(path).parent)


def _make_delimiter(path: str, index: int) -> str:
    """Generate a unique heredoc delimiter for a file.

    Uses SHA-256 of path + index to prevent delimiter collision
    with file content.
    """
    raw = f"{path}:{index}".encode()
    suffix = hashlib.sha256(raw).hexdigest()[:8]
    return f"FILE_EOF_{suffix}"


def generate_batch_manifest(
    profile_name: str,
    session_id: str,
    files: list[dict[str, Any]],
    snapshot_id: str,
) -> dict[str, Any]:
    """Generate a manifest JSON for a batch operation.

    Args:
        profile_name: SSH profile name.
        session_id: Current session ID.
        files: List of dicts with 'path', 'content', and optionally
               'original_checksum', 'original_size', 'original_mode'.
        snapshot_id: Unique snapshot identifier.

    Returns:
        Manifest dict suitable for JSON serialization.
    """
    file_entries = []
    total_bytes = 0
    for f in files:
        content = f.get("content", "")
        content_bytes = content.encode("utf-8") if isinstance(content, str) else content
        new_checksum = hashlib.sha256(content_bytes).hexdigest()
        new_size = len(content_bytes)
        total_bytes += new_size

        path = f["path"]
        filename = _posix_basename(path)

        file_entries.append({
            "path": path,
            "backup_name": f"{filename}.original",
            "original_checksum": f.get("original_checksum", ""),
            "original_size": f.get("original_size", 0),
            "original_mode": f.get("original_mode", "0644"),
            "new_checksum": f"sha256:{new_checksum}",
            "new_size": new_size,
            "status": "pending",
        })

    return {
        "snapshot_id": snapshot_id,
        "profile": profile_name,
        "created_at": datetime.now(timezone.utc).isoformat(),
        "created_by_session": session_id,
        "file_count": len(files),
        "total_bytes": total_bytes,
        "files": file_entries,
    }


def generate_batch_script(
    profile_name: str,
    snapshot_id: str,
    files: list[dict[str, Any]],
    manifest: dict[str, Any],
) -> str:
    """Generate a hardened shell script for batch file writing.

    The script follows this structure:
    1. Preflight: check disk space, verify all target files accessible
    2. Snapshot: copy ALL originals to backup dir BEFORE any modification
    3. Write manifest with file metadata
    4. Apply changes: write each file atomically (temp + mv)
    5. Verify: checksum each written file
    6. Report: output JSON summary
    7. On ANY failure: rollback all from snapshot

    Args:
        profile_name: SSH profile name (used for backup dir).
        snapshot_id: Unique snapshot identifier.
        files: List of dicts with 'path' and 'content' keys.
        manifest: Pre-generated manifest dict.

    Returns:
        Complete shell script as a string.
    """
    file_count = len(files)
    timestamp = datetime.now(timezone.utc).isoformat()

    # Calculate required disk space (3x total content + 10MB headroom)
    required_bytes = max(manifest.get("total_bytes", 0) * 3, 10_485_760)

    # Build script sections
    preflight_checks = _build_preflight_checks(files)
    snapshot_commands = _build_snapshot_commands(files)
    manifest_json = json.dumps(manifest, indent=2)
    apply_commands = _build_apply_commands(files)
    verify_commands = _build_verify_commands(files)
    rollback_commands = _build_rollback_commands(files)

    script = f"""#!/bin/bash
set -euo pipefail
# Auto-generated by Ag3ntum SSHWrite — DO NOT EDIT
# Snapshot: {snapshot_id}
# Files: {file_count}
# Generated: {timestamp}

BACKUP_DIR="$HOME/.ag3ntum-backups/{profile_name}/{snapshot_id}"
MANIFEST="$BACKUP_DIR/manifest.json"
FAILED=0

# --- Rollback handler ---
rollback() {{
  echo '{{"phase":"rollback","status":"running"}}'
{rollback_commands}
  echo '{{"phase":"rollback","status":"complete"}}'
}}
trap rollback ERR

# --- Preflight ---
echo '{{"phase":"preflight","status":"running"}}'
AVAIL=$(df --output=avail -B1 / 2>/dev/null | tail -1 || echo "999999999999")
REQUIRED={required_bytes}
if [ "$AVAIL" -lt "$REQUIRED" ]; then
  echo '{{"phase":"preflight","status":"failed","reason":"disk_space","available":'$AVAIL',"required":'$REQUIRED'}}'
  exit 1
fi

# Check all target files are accessible
{preflight_checks}
echo '{{"phase":"preflight","status":"complete"}}'

# --- Snapshot (ALL files backed up BEFORE any modification) ---
echo '{{"phase":"snapshot","status":"running"}}'
mkdir -p "$BACKUP_DIR"
{snapshot_commands}

# Write manifest
cat > "$MANIFEST" << 'MANIFEST_EOF'
{manifest_json}
MANIFEST_EOF
echo '{{"phase":"snapshot","status":"complete","backup_dir":"'"$BACKUP_DIR"'"}}'

# --- Apply changes (atomic per-file: write tmp, mv) ---
echo '{{"phase":"apply","status":"running"}}'
{apply_commands}
echo '{{"phase":"apply","status":"complete"}}'

# --- Verify ---
echo '{{"phase":"verify","status":"running"}}'
{verify_commands}
echo '{{"phase":"verify","status":"complete"}}'

echo '{{"phase":"complete","status":"success","files":{file_count},"backup_dir":"'"$BACKUP_DIR"'"}}'

# Self-delete
rm -f "$0"
"""
    return script


def _build_preflight_checks(files: list[dict[str, Any]]) -> str:
    """Generate preflight file accessibility checks."""
    lines = []
    for f in files:
        path = f["path"]
        parent = _posix_parent(path)
        lines.append(
            f'if [ ! -d "{parent}" ]; then\n'
            f'  echo \'{{"phase":"preflight","status":"failed",'
            f'"reason":"parent_dir_missing","path":"{path}"}}\'\n'
            f'  exit 1\n'
            f'fi'
        )
    return "\n".join(lines)


def _build_snapshot_commands(files: list[dict[str, Any]]) -> str:
    """Generate commands to copy all originals to backup dir."""
    lines = []
    for f in files:
        path = f["path"]
        backup_name = f"{_posix_basename(path)}.original"
        lines.append(
            f'if [ -f "{path}" ]; then\n'
            f'  cp -a "{path}" "$BACKUP_DIR/{backup_name}"\n'
            f'fi'
        )
    return "\n".join(lines)


def _build_apply_commands(files: list[dict[str, Any]]) -> str:
    """Generate atomic write commands for each file."""
    lines = []
    for i, f in enumerate(files):
        path = f["path"]
        content = f.get("content", "")
        delimiter = _make_delimiter(path, i)
        mode = f.get("original_mode", "0644")

        parent = _posix_parent(path)
        filename = _posix_basename(path)
        temp_path = f"{parent}/.{filename}.ag3ntum-tmp"

        lines.append(
            f'cat > "{temp_path}" << \'{delimiter}\'\n'
            f'{content}\n'
            f'{delimiter}\n'
            f'chmod {mode} "{temp_path}"\n'
            f'mv "{temp_path}" "{path}"'
        )
    return "\n".join(lines)


def _build_verify_commands(files: list[dict[str, Any]]) -> str:
    """Generate checksum verification commands."""
    lines = []
    for f in files:
        path = f["path"]
        content = f.get("content", "")
        content_bytes = content.encode("utf-8") if isinstance(content, str) else content
        expected = hashlib.sha256(content_bytes).hexdigest()
        lines.append(
            f'ACTUAL=$(sha256sum "{path}" 2>/dev/null | cut -d" " -f1 || echo "failed")\n'
            f'if [ "$ACTUAL" != "{expected}" ]; then\n'
            f'  echo \'{{"phase":"verify","status":"failed","path":"{path}"}}\'\n'
            f'  FAILED=1\n'
            f'fi'
        )
    lines.append(
        'if [ "$FAILED" -ne 0 ]; then\n'
        '  echo \'{"phase":"verify","status":"failed","rollback":"triggered"}\'\n'
        '  exit 1\n'
        'fi'
    )
    return "\n".join(lines)


def _build_rollback_commands(files: list[dict[str, Any]]) -> str:
    """Generate rollback commands to restore all files from snapshot."""
    lines = []
    for f in files:
        path = f["path"]
        backup_name = f"{_posix_basename(path)}.original"
        lines.append(
            f'  if [ -f "$BACKUP_DIR/{backup_name}" ]; then\n'
            f'    cp -a "$BACKUP_DIR/{backup_name}" "{path}" 2>/dev/null || true\n'
            f'  fi'
        )
    return "\n".join(lines)
